# Generated by Django 3.0.7 on 2020-06-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Customer Name')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=48, verbose_name='E Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('terms', models.TextField(blank=True, max_length=640, verbose_name='Terms')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Approved'), ('2', 'Unapproved'), ('3', 'Cancel')], default=0, max_length=1, verbose_name='Status')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offermanager.Customer', verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('unit', models.TextField(blank=True, choices=[('AD', 'Ad'), ('M2', 'M2'), ('M3', 'M3'), ('KG', 'Kg')], max_length=2, verbose_name='Unit')),
                ('qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Qty')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Cost')),
                ('tax', models.IntegerField(default=0, verbose_name='Tax')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offermanager.Offer')),
            ],
            options={
                'verbose_name': 'Offer item',
                'verbose_name_plural': 'Offer items',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='Department')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
